spring:
  application:
    name: FinancialAI

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY}
#      chat:
#        options:
#          model: ${OPENAI_MODEL:gpt-4o-mini}
#          temperature: ${OPENAI_TEMPERATURE:0.2}
#
#    mcp:
#      server:
#        enabled: true
#      client:
#        enabled: true
#        server-url: http://localhost:${SERVER_PORT}/.well-known/mcp
#
#server:
#  port: ${SERVER_PORT:8080}
#  error:
#    include-message: always

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.springframework.ai: INFO
    org.springframework.ai.mcp: INFO
    com.FinancialAI: DEBUG

jwt:
  public:
    key: ${JWT_PUBLIC_KEY}
  private:
    key: ${JWT_PRIVATE_KEY}