DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    email       VARCHAR(100)                            NOT NULL,
    password    VARCHAR(100)                            NOT NULL,
    create_time TIMESTAMP                               NOT NULL,
    active      BOOLEAN                                 NOT NULL
);

ALTER TABLE users
    ADD CONSTRAINT pk_users PRIMARY KEY (id);

ALTER TABLE users
    ADD CONSTRAINT uk_users_email UNIQUE (email);

CREATE TABLE category
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(100)                            NOT NULL,
    user_id BIGINT                                  NULL
);

ALTER TABLE category
    ADD CONSTRAINT pk_category PRIMARY KEY (id);

ALTER TABLE category
    ADD CONSTRAINT uk_category_user_name UNIQUE (user_id, name);

ALTER TABLE category
    ADD CONSTRAINT fk_category_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE;

CREATE TABLE transactions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    category_id      BIGINT                                  NOT NULL,
    amount           DECIMAL(10, 2)                          NOT NULL,
    transaction_date DATE                                    NOT NULL,
    description      VARCHAR(255),
    transaction_type VARCHAR(50)                             NOT NULL,
    created_at       TIMESTAMP                               NOT NULL,
    updated_at       TIMESTAMP                               NOT NULL
);

ALTER TABLE transactions
    ADD CONSTRAINT pk_transactions PRIMARY KEY (id);

ALTER TABLE transactions
    ADD CONSTRAINT fk_transactions_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE transactions
    ADD CONSTRAINT fk_transactions_category FOREIGN KEY (category_id)
        REFERENCES category (id) ON DELETE RESTRICT;